### ISSUE TITLE
error while loading shared libraries: libevent_pthreads-2.2.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by bruhhhhhhhhhh7** [WeyCoin/WeyCoin#2]
error while loading shared libraries: libevent_pthreads-2.2.so.1: cannot open shared object file: No such file or directory

Get this error while trying to run weycoind.

http://prntscr.com/i9z3xf

**Comment by ghost** [comment]
I’m guessing this is for Mac OS X? In which case I’m working on a fix. If it’s for ubuntu, I will certainly look into it.

**Comment by SohaibKHN** [comment]
Dependency issue. I didn't install libevent.

**Comment by bedri** [comment]
It's most probably related with libevent version.

**Comment by ghost** [comment]
Ensure you've completely installed all the libraries and dependencies as outlined in the `build` documentation for whatever OS you're using.
