### ISSUE TITLE
Error when trying to build in Ubuntu

### ISSUE THREAD

**Issue by rrrround** [WeyCoin/WeyCoin#3]
When I run sudo ./autogen.sh I get this error message
![error](https://user-images.githubusercontent.com/22407159/35836495-886667a2-0aae-11e8-9203-1bd554b19635.PNG)

**Comment by bruhhhhhhhhhh7** [comment]
This happened to me as well. Check https://github.com/WeyCoin/WeyCoin/blob/master/doc/build-unix.md for the required prerequisites. You can run it but it freezes...

**Comment by bedri** [comment]
1) Don't use sudo (root permissions) to run autogen.sh
2) .cpp files are C plus plus source code files so you cannot run them
3) if autogen.sh is not executable, you cannot run it. You should use command
> chown +x autogen.sh
to make it executable first.
4) maybe it's better for you to use the already compiled version.

Thanks.

**Comment by ghost** [comment]
This issue is closed.
