### ISSUE TITLE
What happened to the discord?

### ISSUE THREAD

**Issue by LSpark** [WeyCoin/WeyCoin#6]

**Comment by esavard** [comment]
That happened: https://bitsonline.com/maple-change-hack-exit-scam/

**Comment by esavard** [comment]
The guy(s) behind WeyCoin was the same behind Maple Coin Exchange.

**Comment by ergot** [comment]
@LSpark flav deleted discord server after the exit scam of his exchange, we have recreated the server here https://discord.gg/Qw22QWD
